### ISSUE TITLE
CallExpression throwing error

### ISSUE THREAD

**Issue by CMatias** [jared-stilwell/escomplex-ast-moz#88]
Whenever I run the following code:

`const file = fs.readFileSync(filePath);`
`const ast = esprima.parse(file, {range: true, comment: true}); `
`const escomplexResult = escomplex.analyse(ast, escomplexWalker);`

an the code has CallExpressions I get the following error: [http://imgur.com/xTcEDzN](screenshot)

This code was previously working for me

**Comment by CMatias** [comment]
This fixed the issue : 

`const ast = esprima.parse(file, {loc: true, range: true, comment: true});`

The indication that the walker needs the loc option should be indicated.

**Comment by jared-stilwell** [comment]
I've refiled this bug under the [escomplex project](https://github.com/jared-stilwell/escomplex/issues/17) since all code and development on the walker is being subsumed by the escomplex project. For more details, see http://beep.beep.boop.online/escomplex-2-alpha/
